todo: ejemplo1 ejemplo2 pi_secuencial pi_paralelo
	
ejemplo1: ejemplo1.c
	gcc -fopenmp ejemplo1.c -o ejemplo1
	
ejemplo2: ejemplo2.c
	gcc -fopenmp ejemplo2.c -o ejemplo2
	
pi_secuencial: pi_secuencial.c
	gcc pi_secuencial.c -o pi_secuencial
	
pi_paralelo: pi_paralelo.c
	gcc -fopenmp pi_paralelo.c -o pi_paralelo